worlds:
    stargate:
    - 597YGSOFT
    - 1FDBTM57X
    - FFDI0MSEH
    thunderbird 5:
    - QAM2Y6ZKY
    - L994QWAYK
    copy of cold desert oil fields:
    - V9VHHAH5W
    - REX532QFD
    - WIKPVGEN4
    cake shop:
    - CGRQN6ITQ
    - L998NVCPN
    - QHYOFTDS4
